# 25 minutes
SHORT_TOMATO_DURATION = 1500

# 50 minutes
LONG_TOMATO_DURATION = 3000

# 5 minutes
SHORT_BREAK_DURATION = 300

# 10 minutes
LONG_BREAK_DURATION = 600

TOMATO_NAME = "Tomato"
BREAK_NAME = "Tomato Break"

TOMATO_TYPE = "Tomato"
BREAK_TYPE = "Break"

PYTOMATO_PROJECTS_DIR = "~/.pytomato"
DEFAULT_PROJECT_NAME = "default"
PROJECT_EXTENSION = ".tomato"

GIT_EXECUTABLE_PATH = ""
GIT_REMOTE_REPOSITORY_URI = ""
